[build]
  command = "npm install --include=optional --force && npm run build"
  publish = "dist"
[build.environment]
  # Força o preset do Nitro para a Netlify
  NITRO_PRESET = "netlify"
  NODE_VERSION = "22"

[context.deploy-preview.environment]
  NITRO_PRESET = "netlify"
[context.branch-deploy.environment]
  NITRO_PRESET = "netlify"
