/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as MecanicosRouteImport } from './routes/mecanicos'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PatioRouteImport } from './routes/patio'
import { Route as PecasRouteImport } from './routes/pecas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AtendimentoIdRouteImport } from './routes/atendimento.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MecanicosRoute = MecanicosRouteImport.update({
  id: '/mecanicos',
  path: '/mecanicos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PatioRoute = PatioRouteImport.update({
  id: '/patio',
  path: '/patio',
  getParentRoute: () => rootRouteImport,
} as any)
const PecasRoute = PecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIdRoute = AtendimentoIdRouteImport.update({
  id: '/atendimento/$id',
  path: '/atendimento/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/caixa': typeof CaixaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/mecanicos': typeof MecanicosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/patio': typeof PatioRoute
  '/pecas': typeof PecasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atendimento/$id': typeof AtendimentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/caixa': typeof CaixaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/mecanicos': typeof MecanicosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/patio': typeof PatioRoute
  '/pecas': typeof PecasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atendimento/$id': typeof AtendimentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/caixa': typeof CaixaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/mecanicos': typeof MecanicosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/patio': typeof PatioRoute
  '/pecas': typeof PecasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atendimento/$id': typeof AtendimentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avisos'
    | '/caixa'
    | '/configuracoes'
    | '/historico'
    | '/mecanicos'
    | '/notificacoes'
    | '/patio'
    | '/pecas'
    | '/reset-password'
    | '/atendimento/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avisos'
    | '/caixa'
    | '/configuracoes'
    | '/historico'
    | '/mecanicos'
    | '/notificacoes'
    | '/patio'
    | '/pecas'
    | '/reset-password'
    | '/atendimento/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/avisos'
    | '/caixa'
    | '/configuracoes'
    | '/historico'
    | '/mecanicos'
    | '/notificacoes'
    | '/patio'
    | '/pecas'
    | '/reset-password'
    | '/atendimento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AvisosRoute: typeof AvisosRoute
  CaixaRoute: typeof CaixaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRoute
  MecanicosRoute: typeof MecanicosRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PatioRoute: typeof PatioRoute
  PecasRoute: typeof PecasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AtendimentoIdRoute: typeof AtendimentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mecanicos': {
      id: '/mecanicos'
      path: '/mecanicos'
      fullPath: '/mecanicos'
      preLoaderRoute: typeof MecanicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patio': {
      id: '/patio'
      path: '/patio'
      fullPath: '/patio'
      preLoaderRoute: typeof PatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecas': {
      id: '/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof PecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/$id': {
      id: '/atendimento/$id'
      path: '/atendimento/$id'
      fullPath: '/atendimento/$id'
      preLoaderRoute: typeof AtendimentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AvisosRoute: AvisosRoute,
  CaixaRoute: CaixaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRoute,
  MecanicosRoute: MecanicosRoute,
  NotificacoesRoute: NotificacoesRoute,
  PatioRoute: PatioRoute,
  PecasRoute: PecasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AtendimentoIdRoute: AtendimentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
